version: 1
disable_existing_loggers: False
formatters:
    time_only: 
        format: '[%(asctime)s]    %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    simple:
        format: '[%(asctime)s] %(levelname)-8s [%(filename)s:%(lineno)d] %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    verbose:
        format: '[%(asctime)s] %(levelname)-8s [%(filename)s:%(lineno)d] %(message)s'
    verbose2:
        format: '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout        
    file-ChatLogger:
        class : logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: verbose
        filename: ChatLogger.log
        maxBytes: 5000000
        backupCount: 3
        encoding: utf-8
root:
    level: DEBUG
    handlers: [console, file-ChatLogger]
        